---
- name: Validation et Hygiène du service Docker
  hosts: localhost
  gather_facts: no

  tasks:
    - name: "Étape 4 : Validation HTTP (code 200 attendu)"
      ansible.builtin.uri:
        url: "http://localhost:8080"
        status_code: 200
      register: http_check
      until: http_check.status == 200
      retries: 5
      delay: 5

    - name: "Étape 5 : Récupération des infos du container"
      community.docker.docker_container_info:
        name: mon_serveur_web
      register: result

    - name: "Vérification de l'état (Running)"
      ansible.builtin.assert:
        that:
          - result.container.State.Running == true
        fail_msg: "Le container n'est pas en cours d'exécution !"

    - name: "Vérification de l'hygiène (Restart Policy)"
      ansible.builtin.assert:
        that:
          - result.container.HostConfig.RestartPolicy.Name == "always"
        fail_msg: "La politique de redémarrage n'est pas conforme."